### ISSUE TITLE
Release Sapphire client v2

### ISSUE THREAD

**Issue by CedarMist** [oasisprotocol/sapphire-paratime#448]
## Release V2 of Sapphire client and deprecate other older packages

Relates to https://github.com/oasisprotocol/sapphire-paratime/issues/242

## TODO

- [x] confirm before deleting branch https://github.com/oasisprotocol/sapphire-paratime/tree/stable/clients/js/1.x (probably keep?)
- [x] bump `sapphire-paratime` in `docs` repo

## Completed

* [x] Request SIWE docs from @matevz
* [x] Update [`demo-starter`](https://github.com/oasisprotocol/demo-starter)

**Comment by rube-de** [comment]
Demo-starter also uses v1. I think would be also good to update it to v2

**Comment by aefhm** [comment]
Maybe we should make a page/guide on migration?

**Comment by aefhm** [comment]
> Demo-starter also uses v1. I think would be also good to update it to v2

Completed via https://github.com/oasisprotocol/demo-starter/pull/16

**Comment by aefhm** [comment]
Let's also close https://github.com/oasisprotocol/sapphire-paratime/issues/242 while we do this.

**Comment by aefhm** [comment]
Consider [this](https://github.com/oasisprotocol/demo-starter/pull/26#issuecomment-2671775200) too.
